// ts/src/react/stitch-admin/tabs.ts
import * as React from 'react';
import { Tabs as AntdTabs } from 'antd';
import type { TabsProps as AntdTabsProps } from 'antd';

import type { TabItem as SharedTabItem } from '../../stitch-admin/tabs-types.js';

const h = React.createElement;

export interface TabItem extends Omit<SharedTabItem, 'label' | 'icon'> {
  /** Display label rendered next to the optional count badge. */
  label: React.ReactNode;
  /** Optional leading icon node. */
  icon?: React.ReactNode;
}

export interface TabsProps {
  /** Tab definitions. Hidden items are filtered out before rendering. */
  items: TabItem[];
  /** Currently selected key. Leave undefined for uncontrolled usage. */
  activeKey?: string;
  /** Default selection when uncontrolled. */
  defaultActiveKey?: string;
  /** Fires with the newly-selected key. */
  onChange?: (key: string) => void;
  /**
   * Optional content for the active tab's panel. When omitted, the Tabs
   * primitive is used purely for navigation — callers render their own
   * content region below based on `activeKey`.
   */
  children?: React.ReactNode;
  /** `line` draws a bottom underline; `card` draws a tonal pill. Default `line`. */
  variant?: 'line' | 'card';
}

function renderLabel(
  label: React.ReactNode,
  icon: React.ReactNode | undefined,
  count: number | undefined,
): React.ReactNode {
  const countNode =
    count !== undefined
      ? h(
          'span',
          {
            className: 'facetheory-stitch-tabs-count',
            style: {
              marginLeft: '8px',
              display: 'inline-flex',
              alignItems: 'center',
              justifyContent: 'center',
              minWidth: '20px',
              height: '18px',
              padding: '0 6px',
              fontSize: '11px',
              fontWeight: 600,
              lineHeight: 1,
              borderRadius: '9999px',
              background: 'var(--stitch-color-surface-container-high, #e2e7ff)',
              color: 'var(--stitch-color-on-surface-variant, #464553)',
            },
          },
          count,
        )
      : null;

  return h(
    'span',
    {
      className: 'facetheory-stitch-tabs-label',
      style: { display: 'inline-flex', alignItems: 'center', gap: '8px' },
    },
    icon !== undefined
      ? h(
          'span',
          {
            className: 'facetheory-stitch-tabs-icon',
            style: { display: 'inline-flex', alignItems: 'center' },
          },
          icon,
        )
      : null,
    h('span', null, label),
    countNode,
  );
}

/**
 * Dense-admin tab bar. Wraps AntD's `Tabs` with Stitch-tonal labels that
 * support an inline count badge and an optional leading icon. Usable as
 * either a content switcher (pass `children`) or pure navigation (omit
 * `children` and render your own content below based on `activeKey`).
 */
export function Tabs(props: TabsProps): React.ReactElement {
  const { items, activeKey, defaultActiveKey, onChange, children, variant } =
    props;

  const visibleItems = items.filter((item) => item.hidden !== true);
  const resolvedActiveKey =
    activeKey ?? defaultActiveKey ?? visibleItems[0]?.key;

  const antdItems: NonNullable<AntdTabsProps['items']> = visibleItems.map(
    (item) => {
      const out: NonNullable<AntdTabsProps['items']>[number] = {
        key: item.key,
        label: renderLabel(item.label, item.icon, item.count),
      };
      if (item.disabled === true) out.disabled = true;
      if (children !== undefined && resolvedActiveKey === item.key) {
        out.children = children;
      }
      return out;
    },
  );

  const antdProps: AntdTabsProps = { items: antdItems };
  if (activeKey !== undefined) antdProps.activeKey = activeKey;
  if (defaultActiveKey !== undefined) {
    antdProps.defaultActiveKey = defaultActiveKey;
  }
  if (onChange !== undefined) antdProps.onChange = onChange;
  if (variant === 'card') antdProps.type = 'card';

  return h(
    'div',
    { className: 'facetheory-stitch-tabs' },
    h(AntdTabs, antdProps),
  );
}

// ts/src/svelte/stitch-admin/Tabs.svelte
<script lang="ts">
  import type { TabItem } from './types.js';

  export let items: TabItem[] = [];
  export let activeKey: string | undefined = undefined;
  export let defaultActiveKey: string | undefined = undefined;
  export let onChange: ((key: string) => void) | undefined = undefined;
  export let variant: 'line' | 'card' = 'line';

  let internalActiveKey = defaultActiveKey;

  $: visibleItems = items.filter((item) => item.hidden !== true);
  $: if (
    activeKey === undefined &&
    internalActiveKey === undefined &&
    visibleItems.length > 0
  ) {
    internalActiveKey = visibleItems[0].key;
  }
  $: resolvedActiveKey = activeKey ?? internalActiveKey;

  function selectTab(item: TabItem): void {
    if (item.disabled) return;
    if (activeKey === undefined) internalActiveKey = item.key;
    onChange?.(item.key);
  }
</script>

<div
  class="facetheory-stitch-tabs"
  style="display:flex;flex-direction:column;gap:12px;"
>
  <div
    class="facetheory-stitch-tabs-bar"
    role="tablist"
    style={`display:flex;flex-wrap:wrap;gap:${variant === 'card' ? '8px' : '24px'};${variant === 'line' ? 'border-bottom:1px solid var(--stitch-color-outline-variant, #c8c4d5);' : ''}`}
  >
    {#each visibleItems as item (item.key)}
      <button
        type="button"
        role="tab"
        aria-selected={item.key === resolvedActiveKey}
        disabled={item.disabled === true}
        class="facetheory-stitch-tabs-trigger"
        on:click={() => selectTab(item)}
        style={`display:inline-flex;align-items:center;gap:8px;padding:${variant === 'card' ? '8px 12px' : '10px 0 12px'};${variant === 'line' ? 'margin-bottom:-1px;' : ''}${variant === 'card' ? 'border:1px solid var(--stitch-color-outline-variant, #c8c4d5);border-radius:var(--stitch-radius-md, 8px);' : 'border:none;'}${variant === 'line' ? `border-bottom:2px solid ${item.key === resolvedActiveKey ? 'var(--stitch-color-primary, #3a48c8)' : 'transparent'};` : ''}background:${variant === 'card' && item.key === resolvedActiveKey ? 'var(--stitch-color-surface-container-low, #f2f3ff)' : 'transparent'};color:${item.disabled ? 'var(--stitch-color-on-surface-variant, #868391)' : item.key === resolvedActiveKey ? 'var(--stitch-color-on-surface, #131b2e)' : 'var(--stitch-color-on-surface-variant, #464553)'};font:inherit;cursor:${item.disabled ? 'default' : 'pointer'};`}
      >
        <span
          class="facetheory-stitch-tabs-label"
          style="display:inline-flex;align-items:center;gap:8px;"
        >
          {#if item.icon !== undefined}
            <span
              class="facetheory-stitch-tabs-icon"
              style="display:inline-flex;align-items:center;"
            >
              {item.icon}
            </span>
          {/if}
          <span>{item.label}</span>
          {#if item.count !== undefined}
            <span
              class="facetheory-stitch-tabs-count"
              style="display:inline-flex;align-items:center;justify-content:center;min-width:20px;height:18px;padding:0 6px;font-size:11px;font-weight:600;line-height:1;border-radius:9999px;background:var(--stitch-color-surface-container-high, #e2e7ff);color:var(--stitch-color-on-surface-variant, #464553);"
            >
              {item.count}
            </span>
          {/if}
        </span>
      </button>
    {/each}
  </div>

  {#if resolvedActiveKey !== undefined && $$slots.default}
    <div class="facetheory-stitch-tabs-panel">
      <slot />
    </div>
  {/if}
</div>
