// ts/src/react/stitch-shell/brand-header.ts
import * as React from 'react';

const h = React.createElement;

export interface BrandHeaderProps {
  /**
   * Brand logo node (icon, image, or custom component). Brand-agnostic —
   * FaceTheory does not bundle any specific logo.
   */
  logo: React.ReactNode;
  /**
   * Brand wordmark — typically the product or platform name. Accepts a
   * string or any ReactNode so a caller can use a custom wordmark component.
   */
  wordmark: React.ReactNode;
  /**
   * Optional surface-chip label (for example a "[Core]" / "[MCP]" / "[Auth]"
   * classification, or any consumer-defined chip text). Omit to render just
   * the logo + wordmark.
   */
  surfaceLabel?: React.ReactNode;
  /**
   * Optional tone hint for the surface chip. The component binds the chip's
   * background and foreground to the CSS variables
   * `--stitch-color-{surfaceTone}-container` and
   * `--stitch-color-on-{surfaceTone}-container`. The tone name is
   * caller-chosen — FaceTheory ships no enumerated vocabulary. When omitted,
   * the chip falls back to neutral surface-container tokens.
   */
  surfaceTone?: string;
}

/**
 * BrandHeader renders a caller-supplied logo + wordmark pair, with an
 * optional surface-chip label on the right. The component is brand-agnostic:
 * all content is caller-provided, all colors bind through Stitch CSS
 * variables, and nothing Theory-Cloud-specific is hard-coded.
 *
 * Typical uses:
 *  - Pass the entire BrandHeader as the `logo` prop of the Topbar from 2.1,
 *    leaving the Topbar's `surfaceLabel` slot unused.
 *  - Pass the logo to Topbar's `logo` slot and render a separate chip
 *    through Topbar's `surfaceLabel` slot.
 *  - Render BrandHeader standalone as a page-level header outside the Shell.
 */
export function BrandHeader(props: BrandHeaderProps): React.ReactElement {
  const { logo, wordmark, surfaceLabel, surfaceTone } = props;

  const chipBg =
    surfaceTone !== undefined
      ? `var(--stitch-color-${surfaceTone}-container, var(--stitch-color-surface-container-high, #e2e7ff))`
      : 'var(--stitch-color-surface-container-high, #e2e7ff)';
  const chipColor =
    surfaceTone !== undefined
      ? `var(--stitch-color-on-${surfaceTone}-container, var(--stitch-color-on-surface, #131b2e))`
      : 'var(--stitch-color-on-surface, #131b2e)';

  return h(
    'div',
    {
      className: 'facetheory-stitch-brand-header',
      style: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '12px',
      },
    },
    h(
      'span',
      {
        className: 'facetheory-stitch-brand-header-logo',
        style: { display: 'inline-flex', alignItems: 'center' },
      },
      logo,
    ),
    h(
      'span',
      {
        className: 'facetheory-stitch-brand-header-wordmark',
        style: {
          fontFamily: 'var(--stitch-font-display, inherit)',
          fontWeight: 600,
          fontSize: '15px',
          letterSpacing: '0.01em',
          color: 'var(--stitch-color-on-surface, #131b2e)',
        },
      },
      wordmark,
    ),
    surfaceLabel !== undefined
      ? h(
          'span',
          {
            className: 'facetheory-stitch-brand-header-surface-label',
            'data-surface-tone': surfaceTone,
            style: {
              display: 'inline-flex',
              alignItems: 'center',
              padding: '2px 10px',
              borderRadius: 'var(--stitch-radius-sm, 4px)',
              background: chipBg,
              color: chipColor,
              fontFamily: 'var(--stitch-font-label, inherit)',
              fontSize: '11px',
              fontWeight: 600,
              letterSpacing: '0.08em',
            },
          },
          surfaceLabel,
        )
      : null,
  );
}

// ts/src/svelte/stitch-shell/BrandHeader.svelte
<!--
  Stitch BrandHeader (Svelte).

  Renders a caller-supplied logo + wordmark pair with an optional surface-chip
  label on the right. Brand-agnostic: all content is caller-provided, all
  colors bind through Stitch CSS variables.

  Props:
    - `logo`         Logo content. Use the prop for simple strings / HTML
                     fragments, or the `logo` named slot for rich content.
    - `wordmark`     Wordmark content (product or platform name). Use the
                     prop for strings, or the `wordmark` named slot for rich
                     content.
    - `surfaceLabel` Optional surface-chip label. Use the prop for strings,
                     or the `surfaceLabel` named slot for rich content.
    - `surfaceTone`  Optional free-form tone hint. Binds the chip's
                     background / foreground to
                     `--stitch-color-{surfaceTone}-container` and
                     `--stitch-color-on-{surfaceTone}-container`. Omit for a
                     neutral chip. FaceTheory ships no enumerated vocabulary.
-->
<script lang="ts">
  export let logo: unknown = undefined;
  export let wordmark: unknown = undefined;
  export let surfaceLabel: unknown = undefined;
  export let surfaceTone: string | undefined = undefined;

  $: chipBg =
    surfaceTone !== undefined
      ? `var(--stitch-color-${surfaceTone}-container, var(--stitch-color-surface-container-high, #e2e7ff))`
      : 'var(--stitch-color-surface-container-high, #e2e7ff)';
  $: chipColor =
    surfaceTone !== undefined
      ? `var(--stitch-color-on-${surfaceTone}-container, var(--stitch-color-on-surface, #131b2e))`
      : 'var(--stitch-color-on-surface, #131b2e)';

  $: hasSurfaceLabel = Boolean($$slots.surfaceLabel) || surfaceLabel !== undefined;
</script>

<div
  class="facetheory-stitch-brand-header"
  style="display:inline-flex;align-items:center;gap:12px;"
>
  <span
    class="facetheory-stitch-brand-header-logo"
    style="display:inline-flex;align-items:center;"
  >
    <slot name="logo">{#if logo !== undefined}{logo}{/if}</slot>
  </span>
  <span
    class="facetheory-stitch-brand-header-wordmark"
    style="font-family:var(--stitch-font-display, inherit);font-weight:600;font-size:15px;letter-spacing:0.01em;color:var(--stitch-color-on-surface, #131b2e);"
  >
    <slot name="wordmark">{#if wordmark !== undefined}{wordmark}{/if}</slot>
  </span>
  {#if hasSurfaceLabel}
    <span
      class="facetheory-stitch-brand-header-surface-label"
      data-surface-tone={surfaceTone}
      style={`display:inline-flex;align-items:center;padding:2px 10px;border-radius:var(--stitch-radius-sm, 4px);background:${chipBg};color:${chipColor};font-family:var(--stitch-font-label, inherit);font-size:11px;font-weight:600;letter-spacing:0.08em;`}
    >
      <slot name="surfaceLabel">{#if surfaceLabel !== undefined}{surfaceLabel}{/if}</slot>
    </span>
  {/if}
</div>
